<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\TbdDevelop.Kafka.Extensions\TbdDevelop.Kafka.Extensions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
        <PackageReference Include="NSubstitute" Version="6.2.0"/>
        <PackageReference Include="xunit.v3" Version="4.0.0"/>
    </ItemGroup>

</Project>
